test_format = 1.0

[default]
    
    # ------------
    # Tests to run
    # ------------
    
    
    
    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    
    
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    
    test_upgrade_from.c1690e4.name = "Upgrade from 2023.1.7~ynh2"
    
